apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "referral-svc.fullname" . }}-config
  labels:
    {{- include "referral-svc.labels" . | nindent 4 }}
data:
  {{- range $key, $value := .Values.envVars }}
  {{ $key }}: {{ $value | toString | quote }}
  {{- end }}
