{{- if .Values.rbac.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "referral-svc.fullname" . }}
  labels:
    {{- include "referral-svc.labels" . | nindent 4 }}
rules:
  {{- toYaml .Values.rbac.rules | nindent 2 }}

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "referral-svc.fullname" . }}
  labels:
    {{- include "referral-svc.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ default (include "referral-svc.fullname" .) .Values.serviceAccount.name }}
    namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "referral-svc.fullname" . }}
{{- end }}
