apiVersion: v1
kind: Secret
metadata:
  name: {{ include "referral-svc.fullname" . }}-secret
  labels:
    {{- include "referral-svc.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- range $key, $value := .Values.secretVars }}
  {{ $key }}: {{ $value | toString | quote }}
  {{- end }}
