{{- if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "referral-svc.fullname" . }}
  labels:
    {{- include "referral-svc.labels" . | nindent 4 }}
    {{- with .Values.serviceMonitor.labels }}{{ toYaml . | nindent 4 }}{{- end }}
spec:
  selector:
    matchLabels:
      {{- include "referral-svc.selectorLabels" . | nindent 6 }}
  namespaceSelector:
    matchNames: [ {{ .Release.Namespace | quote }} ]
  endpoints:
    - port: http
      path: {{ default "/metrics" .Values.metricsPath | quote }}
      interval: {{ default "15s" .Values.serviceMonitor.interval }}
      scrapeTimeout: {{ default "10s" .Values.serviceMonitor.scrapeTimeout }}
      {{- with .Values.serviceMonitor.metricRelabelings }}
      metricRelabelings: {{ toYaml . | nindent 6 }}
      {{- end }}
      {{- with .Values.serviceMonitor.relabelings }}
      relabelings: {{ toYaml . | nindent 6 }}
      {{- end }}
{{- end }}
